language: python
python: "2.7"

install: pip install tox

script: tox

after_script:
    - cat var/log/*
    - ls -lh .coverage*
    - ps -efl

after_success:
    - pip install coveralls
    - coveralls
