language: python
python: "2.7"

env:
    global:
        - TRAVIS_WAIT_TIME=30
    matrix:
        - PTERO_SHELL_COMMAND_TEST_PROCFILE=tests/scripts/Procfile
        - PTERO_SHELL_COMMAND_TEST_PROCFILE=tests/scripts/Procfile-with-sudo

install: pip install tox==1.9.0

before_script: sudo update-alternatives --install /bin/sh sh /bin/bash 100

script:
    - tox

after_script:
    - ps -efl > var/log/ps.out
    - bash -c 'for f in var/log/*; do echo; echo "============================================"; echo $f; echo "============================================"; cat $f; done'

after_success:
    - pip install coveralls
    - coveralls
