language: python
python: "2.7"

addons:
    postgresql: "9.3"

env:
    matrix:
        - PTERO_SHELL_COMMAND_TEST_PROCFILE=tests/scripts/Procfile
        - PTERO_SHELL_COMMAND_TEST_PROCFILE=tests/scripts/Procfile-with-sudo

install: pip install tox

before_script:
    - sudo update-alternatives --install /bin/sh sh /bin/bash 100
    - sudo rabbitmq-plugins disable rabbitmq_management
    - sudo psql -c 'create database ptero_shell_command;' -U postgres

script:
    - tox

after_script:
    - ps -efl > var/log/ps.out
    - bash -c 'for f in var/log/*; do echo; echo "============================================"; echo $f; echo "============================================"; cat $f; done'

after_success:
    - pip install coveralls
    - coveralls
